### ISSUE TITLE
Allow Inline Comments

### ISSUE THREAD

**Issue by Manered** [Manered/Inscript#1]
Example:
```yaml
# Normal Comment
key: value # Inline Comment

# Normal Comment
key: # Inline Comment
  # ...
```
```gradle
// Normal Comment
key = value // Inline Comment

// Normal Comment
key { // Inline Comment
  // ...
}
```

This would mean we need the following in ConfigNode:
```java
@NotNull
Set<String> getComments();

@NotNull
Set<String> getInlineComments();
```
and in ConfigSection:
```java
void inlineComment(final @NotNull String key, final @NotNull String @NotNull ... comments);

@NotNull
@Unmodifiable
Collection<String> getInlineComments(final @NotNull String key);
```
