### ISSUE TITLE
Easier path system to skip section chaining.

### ISSUE THREAD

**Issue by Manered** [Manered/Inscript#3]
Let's say we have something like this:
```yml
items:
  item_name:
    slot: 10
    item:
      enchantments: []
```
To access the last scalar node `enchantments`, we would need to do:
```java
root.section("items", items -> items.section("item_name", itemName -> itemName.section("item", item -> {
  /* Finally here. */
})));
```
The easier way to skip all of the unused sections will be:
```java
root.section("items.item_name.item", section -> {
  /* finally here */
});
```
But we can also just do:
```java
root.getList("items.item_name.item.enchantments", String.class);
```

The behaviour should be recursively creating previous nodes.
